version: '3.8'

services:
  # PostgreSQL Modern (Prisma) - Production Database
  postgres:
    image: postgres:15-alpine
    container_name: invs-modern-db
    restart: always
    environment:
      POSTGRES_DB: invs_modern
      POSTGRES_USER: invs_user
      POSTGRES_PASSWORD: invs123
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - invs-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U invs_user -d invs_modern"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MySQL Original (Legacy) - Reference Only
  mysql-original:
    image: mariadb:10.11
    container_name: invs-mysql-original
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: invs123
      MYSQL_DATABASE: invs_banpong
      MYSQL_USER: invs_user
      MYSQL_PASSWORD: invs123
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone=+07:00
    networks:
      - invs-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pinvs123"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin - PostgreSQL Management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: invs-modern-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@invs.local
      PGADMIN_DEFAULT_PASSWORD: invs123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8081:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - invs-network

  # phpMyAdmin - MySQL Management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: invs-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql-original
      PMA_PORT: 3306
      PMA_USER: invs_user
      PMA_PASSWORD: invs123
      MYSQL_ROOT_PASSWORD: invs123
    ports:
      - "8082:80"
    depends_on:
      mysql-original:
        condition: service_healthy
    networks:
      - invs-network

volumes:
  postgres_data:
    driver: local
  mysql_data:
    driver: local

networks:
  invs-network:
    driver: bridge